<?php 
session_start();
unset($_SESSION['username']);
unset($_SESSION['password']);
unset($_SESSION['fname']);
unset($_SESSION['lname']);
unset($_SESSION['designation']);
unset($_SESSION['id']);
unset($_SESSION['email']);
session_destroy();
header('location:login.php');
?>